version: 2.0
jobs:
  build:
    working_directory: ~/wksh
    docker:
      - image: microsoft/aspnetcore-build:2.0.0-preview1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "shanghaiwalk/shanghaiwalk.csproj" }}
      - run: |
          sh script/restore
          sh script/build 
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "shanghaiwalk/shanghaiwalk.csproj" }}
          paths:
            - "/root/.nuget/packages"
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - deploy: 
          name: push to registry
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG=1.0.$CIRCLE_BUILD_NUM
              docker build --rm=false  -t kwok/wkshanghai:$TAG .
              docker login -u $DOCKER_USER  -p $DOCKER_PASSWORD  -e $DOCKER_EMAIL  registry.cn-hangzhou.aliyuncs.com
              docker tag kwok/wkshanghai:$TAG registry.cn-hangzhou.aliyuncs.com/kwok/wkshanghai:$TAG
              docker tag kwok/wkshanghai:$TAG registry.cn-hangzhou.aliyuncs.com/kwok/wkshanghai:1.0
              docker push registry.cn-hangzhou.aliyuncs.com/kwok/wkshanghai:$TAG
              docker push registry.cn-hangzhou.aliyuncs.com/kwok/wkshanghai:1.0
            fi

#notify:
#  webhooks:
#    - url：http://