jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:1.1.2
test:
  override:
    - sh script/test
    - if [[ -e test-results.xml ]]; then cp test-results.xml $CIRCLE_TEST_REPORTS/test-results.xml; fi
  post:
    - sh script/build
    - cp -R bin/Release/netcoreapp1.1/ $CIRCLE_ARTIFACTS/
deployment:
  master:
    branch: master
    commands:
      - sh script/publish-dockerhub 
#notify:
#  webhooks:
#    - url：http://